nat_image_id: 'ami-893f53b3'
nat_instance_type: 't2.micro'
environment: 'Test'
availability_zone1: 'ap-southeast-2a'
availability_zone2: 'ap-southeast-2b'
web_image_id: 'ami-910623f2'
web_instance_type: 't2.small'
asg_min_instances: '#'
public_company_cidr: '#.#.#.#/#'
vpc_cidr: '#.#.#.#/#'
public_subnet_az1_cidr: '#.#.#.#/#'
public_subnet_az2_cidr: '#.#.#.#/#'
private_subnet_az1_cidr: '#.#.#.#/#'
private_subnet_az2_cidr: '#.#.#.#/#'
public_cidr: '0.0.0.0/0'
public_subnet_name: 'PublicSubnet'
private_subnet_name: 'PrivateSubnet'
web_server_az1_user_data: '#!/bin/sh\n echo "Hello World"'
web_server_az2_user_data: '#!/bin/sh\n echo "Hello World"'
bootstrap_s3_deploy_repo: 'Some-Bucket-Name'
bootstrap_script_name: 'some-script-name.sh'
