#!/usr/bin/env python

# pylint: disable=missing-docstring, invalid-name, line-too-long, redefined-outer-name, too-many-arguments
import sys
from amazonia.cftemplates import SingleAZenv
from amazonia.amazonia_resources import *

def main(args):
    keypair = args[0]
    appname = args[1]
    bootstrap_location = args[2]

    bootstrap_file= open(bootstrap_location)
    userdata = bootstrap_file.read()

    template = SingleAZenv(keypair)

    HTTP_PORT="80"      # This variable is used to specify the port for general HTTP traffic
    HTTP_PORT_TC="8080"      # This variable is used to specify the port for general HTTP traffic
    HTTPS_PORT="443"    # This variable is used to specify the port for general HTTPS traffic
    IAM_INSTANCE_PROFILE = "instance-iam-role-InstanceProfile-OGL42SZSIQRK"
    SSH_PORT="22"       # SSH Port

    web_sg = add_security_group(template, template.vpc)

    # WEB Rules
    # 80, 443, and 8080 from ELB security group
    # all to NAT security group
    add_security_group_ingress(template, web_sg, "tcp", HTTP_PORT, HTTP_PORT, cidr=PUBLIC_CIDR)
    add_security_group_ingress(template, web_sg, "tcp", HTTP_PORT_TC, HTTP_PORT2, cidr=PUBLIC_CIDR)
    add_security_group_ingress(template, web_sg, "tcp", HTTPS_PORT, HTTPS_PORT, cidr=PUBLIC_CIDR)
    add_security_group_ingress(template, web_sg, "tcp", SSH_PORT, SSH_PORT, cidr=PUBLIC_CIDR)
    add_security_group_egress(template, web_sg, "-1", "-1", "-1", cidr=PUBLIC_CIDR)

    web_launch_config = add_launch_config(template, keypair, [web_sg], WEB_IMAGE_ID, WEB_INSTANCE_TYPE, userdata=userdata)
    web_launch_config.IamInstanceProfile = IAM_INSTANCE_PROFILE
    web_asg = add_auto_scaling_group(template, 1, [template.public_subnet], launch_configuration=web_launch_config, dependson=[template.internet_gateway], app_name=appname)

    print(template.to_json(indent=2, separators=(',', ': ')))

if __name__ == "__main__":
    main(sys.argv[1:])
