#!/usr/bin/env python

# pylint: disable=missing-docstring, invalid-name, line-too-long, redefined-outer-name, too-many-arguments

from troposphere import Template

from amazonia.cftemplates import create_vpc, addSingleAZenv 

def main():
    template = Template()
    vpc = create_vpc(template, "VPC", "10.1.0.0/16", "BILL-TEST")
    addSingleAZenv(template, vpc) 
    print(template.to_json())

if __name__ == "__main__":
    main()
