#!/usr/bin/env python

# pylint: disable=missing-docstring, invalid-name, line-too-long, redefined-outer-name, too-many-arguments

from troposphere import Template

from amazonia.cftemplates import create_VPC, add_AZnetwork 

def main():
    template = Template()
    vpc = create_VPC(template, "TestVPC", "10.1.0.0/16", "BILL-TEST")
    add_AZnetwork(template,vpc) 
    print(template.to_json())

if __name__ == "__main__":
    main()
