#!/usr/bin/env python

# pylint: disable=missing-docstring, invalid-name, line-too-long, redefined-outer-name, too-many-arguments

from troposphere import Template

from amazonia.cftemplates import addVPC, addDualAZenv

def main():
    template = Template()
    vpc = addVPC(template)
    addDualAZenv(template, vpc, "ShaneBYOD")
    print(template.to_json(indent=2, separators=(',', ': ')))

if __name__ == "__main__":
    main()
