#!/usr/bin/env python

# pylint: disable=missing-docstring, invalid-name, line-too-long, redefined-outer-name, too-many-arguments

from troposphere import Template

from amazonia.cftemplates import create_singleAZenv

def main():
    template = Template()
    create_singleAZenv(template, "", "")
    print(template.to_json())

if __name__ == "__main__":
    main()
